#!/usr/bin/env bash

pushd >/dev/null "${GITHUB_WORKSPACE:-.}"
source .github/functions/bash/cache.func.inc.sh
popd >/dev/null

set -euo pipefail

script_dir="$(dirname "$0")"
script_name="$(basename "$0")"

parent_dir="$(realpath -L -e "${script_dir}/..")"

url="$1"
outfile="$3"

cachedir="${CACHE_ROOT:-"${parent_dir}/download-cache"}/get-tarball"
cachefile="${cachedir}/${outfile}"

[ -d "${cachedir}" ] || mkdir -v -p "${cachedir}"

if [ -s "${cachefile}" ]; then
    cp -v "${cachefile}" "${outfile}"
else
    printf -- '%s\t%s\n' "${outfile}" "${url}" | tee -a "${cachedir}/.urls"
    curl -sS --fail --location --remote-time --retry 3 -o "${outfile}" "${url}" && \
        cp -v "${outfile}" "${cachefile}"
fi
