#!/usr/bin/env bash

set -euxo pipefail

url="$1"
outfile="$3"

#root=$(readlink -f -- "$(dirname -- "$0")/..")
root="$(perl -MCwd -e 'print Cwd::abs_path(shift)' "$(dirname -- "$0")/..")"
work="${root}/work"
cachefile="${work}/${outfile}"

[ -d "${work}" ] || mkdir -v "${work}"

if [ -s "${cachefile}" ]; then
    cp -v "${cachefile}" "${outfile}"
else
    printf -- '%s\t%s\n' "${outfile}" "${url}" | tee -a "${work}/.urls"
    curl --progress-bar --fail --location --remote-time --retry 3 -o "${outfile}" "${url}" && \
        cp -v "${outfile}" "${cachefile}"
fi
